/*
 * Copyright (c) 2026 Catalin Dordea and Spring Prism Contributors
 *
 * Licensed under the EUPL, Version 1.2 or later (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */
package io.github.catalin87.prism.core;

import static org.assertj.core.api.Assertions.assertThat;

import io.github.catalin87.prism.core.ruleset.EuropeRulePack;
import io.github.catalin87.prism.core.ruleset.UniversalRulePack;
import io.github.catalin87.prism.core.token.HmacSha256TokenGenerator;
import io.github.catalin87.prism.core.vault.DefaultPrismVault;
import java.util.List;
import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.constraints.StringLength;

/**
 * Foundational property-based testing framework serving as the template for all Prism rule packs.
 * Enforces the "Fail Open" architectural constraint, ensuring detectors never throw unhandled
 * exceptions (like StringIndexOutOfBounds) when processing malicious Unicode structures.
 */
public class PrismPropertyTest {

  private static final byte[] SECRET = "property-test-secret-key-material!!".getBytes();

  /**
   * Every detector should fail open by not throwing on arbitrary Unicode input.
   *
   * @param maliciousUnicodeText A dynamically fuzz-tested arbitrary text buffer generated by jqwik.
   */
  @Property(tries = 1000)
  void detectorsDoNotCrashOnComplexUnicodeInput(
      @ForAll @StringLength(max = 2500) String maliciousUnicodeText) {
    List<PrismRulePack> packs = List.of(new UniversalRulePack(), new EuropeRulePack());

    for (PrismRulePack pack : packs) {
      for (PiiDetector detector : pack.getDetectors()) {
        List<PiiCandidate> candidates = detector.detect(maliciousUnicodeText);
        assertThat(candidates).isNotNull();
      }
    }
  }

  /** Random Unicode payloads should survive tokenization and detokenization intact. */
  @Property(tries = 500)
  void vaultRoundTripsArbitraryUnicode(@ForAll @StringLength(max = 512) String rawText) {
    DefaultPrismVault vault = new DefaultPrismVault(new HmacSha256TokenGenerator(), SECRET, 3600L);

    PrismToken token = vault.tokenize(rawText, "CUSTOM");

    assertThat(token).isNotNull();
    assertThat(vault.detokenize(token.key())).isEqualTo(rawText);
  }
}
